### PR TITLE
Fix AM/PM TimePicker

### PR DESCRIPTION
**Pull request by jackhopner**
Was running into a bug with the DateTimePicker which prevented me changing the `hour` when using AM/PM mode.

The changes I've made solve the issue but not entirely sure if they're the correct way to go about fixing it.

### CODE REVIEW

**Comment by commandiron** [comment]
thanks for your contribution, I will check this issue and changes.

**Comment by commandiron** [comment]
May I know what bug you encountered and what was the code snipplet you used? i guess Negative index thrown an error. Im glad your suggested solution worked for you but these changes break the backwardsDisabled feature. Thanks again for your effort. i will look for another solution for this problem.

**Comment by jackhopner** [comment]
> May I know what bug you encountered and what was the code snipplet you used? i guess Negative index thrown an error. Im glad your suggested solution worked for you but these changes break the backwardsDisabled feature. Thanks again for your effort. i will look for another solution for this problem.

@commandiron When using the `WheelDateTimePicker` like so:

``` WheelDateTimePicker(
            modifier = pickerModifier,
            startDateTime = value,
            timeFormat = TimeFormat.AM_PM,
            onSnappedDateTime = onChange,
            size = DpSize(256.dp, 64.dp),
        )
```

I'm not able to change the hour while `PM` is selected (it just reverts back to 12 after changing), because the hour value it was trying to set it to was > 12 (given it's PM).

**Comment by commandiron** [comment]
this problem starts where you point. I will fix this with another solution (I will switch to the localtime to index with the localTimeToAmPmHour function) and publish a new version. Thank you very much for the feedback.

**Comment by commandiron** [comment]
hey, i release a new [version](https://github.com/commandiron/WheelPickerCompose/releases/tag/1.1.7) for fix this bug. Thanks.

**Pull request closed without merging**
